### DISCUSSION TITLE
Maximum call stack size exceeded

### DISCUSSION THREAD

**Discussion by jasonwaters** [steilerDev/icloud-photos-sync#229] [Q&A]
Hello there, i'm very excited to get started using this tool, thank you for creating it!

I've set up a docker container to run on my synology nas.  My docker-compose file incldues this:

```yaml
  icloud-photos-sync-jason:
    image: steilerdev/icloud-photos-sync:latest
    container_name: icloud-photos-sync-jason
    restart: unless-stopped    
    environment:
      - APPLE_ID_USER=${APPLE_ID_JASON}
      - APPLE_ID_PWD=${APPLE_ID_PASS_JASON}
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - SCHEDULE=* 4 * * *
      - REMOTE_DELETE=false
      - ENABLE_CRASH_REPORTING=false
      - DOWNLOAD_THREADS=5
      - MAX_RETRIES=Infinity
      - METADATA_RATE=1/20
    ports:
      - 6841:80
    volumes:
      - /volume1/documents/icloud_photos/jason:/opt/icloud-photos-library
```

I have authenticated fine, but when i try to do the initial sync i get this error:

```text
Loading local & fetching remote iCloud Library state...
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Experienced fatal error at 3/25/2023, 9:27:21 PM: APP_SYNC (FATAL): Sync failed caused by ICLOUD_PHOTOS_FETCH_RECORDS (FATAL): Unable to fetch records (album 'All photos') caused by Maximum call stack size exceeded (Error Code: 7478eb6d-cd80-4600-874e-b9db675ce947)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Any idea what I might be doing wrong? 

I should also point out that I have a very large photo library with more than 144K photos and 5K videos.
