### DISCUSSION TITLE
about identification host

### DISCUSSION THREAD

**Discussion by sms-ebarbeito** [steilerDev/icloud-photos-sync#563] [Q&A] [answered]
Hello, I have a quick question, I have a docker running on my linux laptop, the docker compose is like this:

```
version: '2'
services:
  photos-sync:
    image: steilerdev/icloud-photos-sync:latest
    container_name: photos-sync
    ports:
      - '19000:80'
    user: 1000:1000 
    environment:
      APPLE_ID_USER: "xxxxxxx@xxxxx.com"
      APPLE_ID_PWD: "xxxxxxxx"
      TZ: "America/Buenos_Aires"                                                       
      SCHEDULE: "0 * * * *"
      ENABLE_CRASH_REPORTING: true
    volumes:
      - /home/xxxxx/Pictures/icloud:/opt/icloud-photos-library
```

every time that I restart the container or restart the laptop, on next execution event I receive a mail from apple saying that my Id was used to start session on a web explorer. There is a way to avoid this mails such a browser identification or something?
