### ISSUE TITLE
Unable to login, ADP is off and WebUI access works

### ISSUE THREAD

**Issue by steeeeev0** [steilerDev/icloud-photos-sync#280]
**Checklist before opening an issue**
- [ X ] Tried the sync a couple of times and the issue is persisting
- [ X ] Checked out [known issues](https://github.com/steilerDev/icloud-photos-sync/labels/known%20issue)
- [ X ] Enabled [crash and error reporting](https://steilerdev.github.io/icloud-photos-sync/user-guides/error-reporting/)

**Describe the bug**

Hello! I have just put together a docker instance of the app and can't seem to authenticate. The exact error message isn't covered in any other issues, so I figured I'd post here.

I have Access iCloud Data on the Web turned **on** (I enabled this earlier today using Settings on my Mac) and have Advanced Data Protection turned **off**. I am able to log into icloud.com using Chrome: when I type in my email address and password, I get a push notification on my devices that I accept and then see an MFA code.

Using this app, I get the following error and am never prompted to accept a login attempt on any of my devices. My Apple ID user and password entries in the environment variables are correct, they are exactly the same as I input them into Chrome which got me into the WebUI successfully.

Here is my `docker-compose.yml` file:
```
version: '2'
services:
  icloud-photos-sync:
    image: 'steilerdev/icloud-photos-sync:latest'
    container_name: icloud-photos-sync
    user: '1000:1000'
    environment:
      APPLE_ID_USER: 'email@domain.com'
      APPLE_ID_PWD: 'password'
      TZ: 'America/Chicago'
      SCHEDULE: '* 16 * * *'
      ENABLE_CRASH_REPORTING: true
    volumes:
      - '/media/internal/streaming/Files/iCloud-Photos:/opt/icloud-photos-library'

```

**Error code**

```
---------------------------------------------------------------------------------------------------------------------------
Welcome to icloud-photos-sync, v.1.1.0!
Made with <3 by steilerDev
---------------------------------------------------------------------------------------------------------------------------
Authenticating user...
---------------------------------------------------------------------------------------------------------------------------
Experienced fatal error at 6/28/2023, 3:11:45 PM: APP_TOKEN (FATAL): Unable to acquire trust token caused by AUTH_FAILED (FATAL): iCloud Authentication failed caused by AUTH_UNAUTHORIZED (FATAL): Username/Password does not seem to match caused by Request failed with status code 401 (Error Code: 0c717c88-4b15-4ccf-bc42-cb6896438d36)
---------------------------------------------------------------------------------------------------------------------------
```

**Logs**

Please paste the log file (preferably with `LOG_LEVEL=debug`), located in `.icloud-photos-sync.log`, stored in the `DATA_DIR`.

```
[2023-06-28T20:11:44.406Z] INFO i-Cloud: Initiating iCloud connection
[2023-06-28T20:11:44.504Z] INFO i-Cloud: Authenticating user
[2023-06-28T20:11:45.614Z] ERROR Error-Handler: APP_TOKEN (FATAL): Unable to acquire trust token caused by AUTH_FAILED (FATAL): iCloud Authentication failed caused by AUTH_UNAUTHORIZED (FATAL): Username/Password does not seem to match caused by Request failed with status code 401 (Error Code: 0c717c88-4b15-4ccf-bc42-cb6896438d36)
```

**Operating environment**
 - OS: Ubuntu 22.04
 - Version: v.1.1.0
 - Execution environment: Docker
