### ISSUE TITLE
AUTH_FAILED: iCloud Authentication failed caused by AUTH_SRP_INIT_FAILED

### ISSUE THREAD

**Issue by tomwilde** [steilerDev/icloud-photos-sync#559]
### Describe the issue

Hi,

I followed the get started page here: https://icps.steiler.dev/get-started/ but on the token request it fails for me..

`docker exec -t photos-sync icloud-photos-sync token`

The specific error I get is:
```
Error: APP_TOKEN: Unable to acquire trust token caused by AUTH_FAILED: iCloud Authentication failed caused by AUTH_SRP_INIT_FAILED: Unable to initialize SRP authentication protocol caused by connect ECONNREFUSED 17.179.252.64:443 (error code: daf4b6e9-4a4f-4d52-9cb5-3549aae08db1)
```
 
With the docker compose setup as:
```
version: '2'
services:
  photos-sync:
    image: steilerdev/icloud-photos-sync:latest
    container_name: photos-sync
    user: 1000:1000
    environment:
      APPLE_ID_USER: "*************"
      APPLE_ID_PWD: "*************"
      TZ: "Europe/London"
      SCHEDULE: "* 2 * * *"
      ENABLE_CRASH_REPORTING: "true"
    volumes:
      - /home/tom/Photos/icloud:/opt/icloud-photos-library
```

I'm running `v.1.3.0`

I can wget: `https://www.google.com` so that rules out connectivity.

Suggestions welcome as this looks _really_ great!

### How to reproduce the behavior?

Follow docker-compose get started setup and run:
`docker exec -t photos-sync icloud-photos-sync token`

### Error Code

AUTH_SRP_INIT_FAILED

### Relevant log output

```shell-script
Authenticating user...
Error: APP_TOKEN: Unable to acquire trust token caused by AUTH_FAILED: iCloud Authentication failed caused by AUTH_SRP_INIT_FAILED: Unable to initialize SRP authentication protocol caused by connect ECONNREFUSED 17.179.252.64:443 (error code: daf4b6e9-4a4f-4d52-9cb5-3549aae08db1)
```

### Operating system

Ubuntu

### Execution environment

docker-compose

### icloud-photos-sync version

v.1.3.0

### Checklist

- [X] This is an [issue](https://github.com/steilerDev/icloud-photos-sync/blob/beta/CONTRIBUTING.md#-found-a-bug) and not [a question](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#question) or [feature request](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#feature)
- [X] The sync was performed a couple of times and the issue is persisting and consistent
- [X] Checked out [open and known issues](https://github.com/steilerDev/icloud-photos-sync/issues?q=is%3Aopen+is%3Aissue+label%3Aclass%28bug%29%2Cclass%28improvement%29%2C%22class%28known+issue%29%22)
- [X] Enabled [crash and error reporting](https://icps.steiler.dev/user-guides/cli/#enable-crash-reporting)
