### ISSUE TITLE
Docker image usage issue on raspberry pi

### ISSUE THREAD

**Issue by puliaiev** [steilerDev/icloud-photos-sync#568]
### Describe the issue

I use the docker image on my pi and it shows `The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

### How to reproduce the behavior?

`docker compose up -d` as described in Get started but from raspberry pi 4
My compose file
```
version: '3.8'
services:
...
  photos-sync:
    image: steilerdev/icloud-photos-sync:latest
    tty: true
    stdin_open: true
    container_name: photos-sync
    # user: <uid>:<gid> 
    environment:
      # APPLE_ID_USER: "<iCloud Username>"
      # APPLE_ID_PWD: "<iCloud Password>"
      TZ: "Europe/Berlin"                                                       
      SCHEDULE: "* 2 * * *"
      ENABLE_CRASH_REPORTING: true
    volumes:
      - /mnt/external-apple-photos:/opt/icloud-photos-library
```

### Error Code

-

### Relevant log output

```shell-script
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

### Operating system

Debian GNU/Linux 11 (bullseye)

### Execution environment

docker

### icloud-photos-sync version

latest

### Checklist

- [X] This is an [issue](https://github.com/steilerDev/icloud-photos-sync/blob/beta/CONTRIBUTING.md#-found-a-bug) and not [a question](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#question) or [feature request](https://github.com/steilerDev/icloud-photos-sync/blob/main/CONTRIBUTING.md#feature)
- [X] The sync was performed a couple of times and the issue is persisting and consistent
- [X] Checked out [open and known issues](https://github.com/steilerDev/icloud-photos-sync/issues?q=is%3Aopen+is%3Aissue+label%3Aclass%28bug%29%2Cclass%28improvement%29%2C%22class%28known+issue%29%22)
- [X] Enabled [crash and error reporting](https://icps.steiler.dev/user-guides/cli/#enable-crash-reporting)
